# Generated by Django 6.0.5 on 2026-05-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
