# Generated by Django 6.0.5 on 2026-05-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='torneo',
        ),
        migrations.AddField(
            model_name='partido',
            name='liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='Estadisticas.liga'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.IntegerField(default=0),
        ),
    ]
