# Generated by Django 6.0.5 on 2026-05-28 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estadisticas', '0002_remove_partido_torneo_partido_liga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugadores', models.ManyToManyField(blank=True, to='Estadisticas.jugador')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_ideal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
